input:
  job:
    package-manager: github_actions
    allowed-updates:
      - update-type: all
    dependency-groups:
      - name: actions
        rules:
          patterns:
            - "*"
    source:
      directory: "/"
      provider: github
      repo: vdaas/vald-ci-labs

# input:
#   job:
#     package-manager: npm_and_yarn
#     allowed-updates:
#       - update-type: all
#     dependency-groups:
#       - name: npm
#         rules:
#           patterns:
#             - "*"
#     source:
#       directory: "/"
#       provider: github
#       repo: vdaas/vald-ci-labs

# job:
#   package-manager: npm_and_yarn
#   allowed-updates:
#     - update-type: all
#   dependency-groups:
#     - name: npm
#       rules:
#         patterns:
#           - "*"
#   source:
#     directory: "/"
#     provider: github
#     repo: vdaas/vald-client-node
