name: "Wait for Docker Images"
description: "Wait for Docker images to be published"
inputs:
  images:
    description: "image names"
    required: false
    default: "vdaas/vald-agent-ngt \
      vdaas/vald-discoverer-k8s \
      vdaas/vald-lb-gateway \
      vdaas/vald-manager-index"
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Wait for images
      shell: bash
      id: wait_for_images
      run: |
        tag=$(cat versions/VALD_VERSION)
        for image in ${IMAGES}
        do
          echo "searching ${image}:${tag}"
          until curl -s "https://registry.hub.docker.com/v2/repositories/${image}/tags/${tag}" | jq '.name' | grep -v "null"; do
            echo "waiting for ${image}:${tag} to be uploaded..."
            sleep 2
          done
        done
      env:
        IMAGES: ${{ inputs.images }}
