name: "Setup Helm environment"
description: "Setup Helm environment"

inputs:
  helm-version:
    description: "The Helm version to use. The default version is `versions/HELM_VERSION`"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Fetch helm version
      id: helm_version
      shell: bash
      run: |
        HELM_VERSION=${HELM_VERSION:-`make version/helm`}

        echo "version=${HELM_VERSION}" >> $GITHUB_OUTPUT
      env:
        HELM_VERSION: ${{ inputs.helm-version }}
    - uses: azure/setup-helm@v3
      with:
        helm-version: ${{ steps.helm_version.outputs.version }}
    - uses: Check helm version
      name: bash
      run: |
        helm version
