name: "Detect Git ref"
description: "Detect Git ref"
outputs:
  REF:
    description: "specifies Git ref"
    value: ${{ steps.detect_git_ref.outputs.REF }}
runs:
  using: "composite"
  steps:
    - name: "Detect Git ref"
      id: detect_git_ref
      shell: bash
      run: |

