name: "Detect CI container image tag"
on:
  workflow_call:

env:
  TARGET_IMAGE: vdaas/vald-ci-container

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Determine Docker image tag
        id: determine_tag_name
        uses: ./.github/actions/determine-docker-image-tag

      - name: Detect Docker image tag for primary
        id: detect_primary_tag_name
        uses: ./.github/actions/detect-docker-image-tags
        with:
          images: ${{ env.TARGET_IMAGE }}
          tag_name: ${{ steps.determine_tag_name.outputs.PRIMARY_TAG }}

      - name: Detect Docker image tag for secondary
        id: detect_default_tag_name
        uses: ./.github/actions/detect-docker-image-tags
        with:
          images: ${{ env.TARGET_IMAGE }}
          tag_name: ${{ steps.determine_tag_name.outputs.DEFAULT_TAG }}

      - name: Merge Docker image tag detection results
        run: |
          TAG_NAME="nightly"

          if [ -n "${DEFAULT_TAG}" ]; then
            # TODO
          fi

          if [ -n "${PRIMARY_TAG}" ]; then
            # TODO
          fi

          echo "TAG_NAME=${TAG_NAME}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT
        env:
          PRIMARY_TAG: ${{ steps.detect_primary_tag_name.outputs.IMAGE_TAGS }}
          DEFAULT_TAG: ${{ steps.detect_default_tag_name.outputs.IMAGE_TAGS }}
