name: "Build docker image"
on:
  workflow_call:
    inputs:
      target:
        type: string
        description: 'Build target. e.g. `agent-ngt`'
        required: true

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dump-context

  build:
    runs-on: ubuntu-latest
    # TODO: Add if statement
    steps:
      - name: 'Get ref'
        id: ref
        shell: bash
        run: |
          if [ ${{ github.event.pull_request.head.sha }} != "" ]; then
            echo ref=${{ github.event.pull_request.head.sha }} >> $GITHUB_OUTPUT
          else
            echo ref=${{ github.sha }} >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}
          set-safe-directory: true
          ref: ${{ steps.ref.outputs.ref }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: "--debug"

  slack:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/notify-slack
        with:
          author_name: "helm-operator image build"
          slack_webhook_url: dummy
