name: "Check HEAD commit difference"
on:
  workflow_call:
    inputs:
      vald_checkout_src_ref:
        description: "Switch branches or restore working tree files to check HEAD commit difference"
        type: string
        default: main
        required: false
      client_checkout_target_ref:
        description: "Switch branches or restore working tree files to check HEAD commit difference"
        type: string
        default: main
        required: false
    secrets:
      CI_TOKEN:
        required: true
env:
  CI_TOKEN: ${{ secrets.CI_TOKEN }}

jobs:
  check-main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.client_checkout_target_ref }}
          token: ${{ env.CI_TOKEN }}
      - name: Set Git config
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Clone Vald repository
        run: |
          make vald/clone && make VALD_CHECKOUT_REF=${VALD_CHECKOUT_REF} vald/checkout
          make vald/origin/sha/print
        env:
          VALD_CHECKOUT_REF: ${{ inputs.vald_checkout_src_ref }}
