name: "Build protobuf"

on:
  # TODO: Delete it later.
  push:
    branches:
      - "add-dump-action"

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dump-context

  build:
    name: build all
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vdaas/vald/vald-ci-container:nightly
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}
          set-safe-directory: true
      - name: build protobuf
        run: |
          make proto/all
