name: "Upload artifacts to release"
on:
  release:
    type:
      - created

  # TODO: Delete it later.
  push:
    branches:
      - "add-dump-action"

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dump-context

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vdaas/vald/vald-ci-container:nightly
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
          path: ${{ github.workspace }}
          set-safe-directory: true
      - uses: ./.github/actions/setup-go
      - name: check
        run: |
          go version

      # TODO: uncomment the following steps
      # - name: Build and zip
      #   run: |
      #     make binary/build/zip
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: artifacts-linux
      #     path: ./artifacts/
