name: "Upload artifacts to release"

on:
  release:
    type:
      - created

  # TODO: Delete it later.
  push:
    branches:
      - "add-dump-action"

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dump-context

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vdaas/vald/vald-ci-container:nightly
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - name: Set Git config
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - uses: ./.github/actions/setup-go

      - uses: ./.github/actions/setup-yq
        with:
          yq_version: 3.2.1

      - name: Check
        run: |
          yq --version

      # TODO: uncomment the following steps
      # - name: Build and zip
      #   run: |
      #     make binary/build/zip
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: artifacts-linux
      #     path: ./artifacts/
