name: "Upload artifacts to release"
on:
  release:
    type:
      - created

  # TODO: Delete it later.
  push:
    branches:
      - "add-dump-action"

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dump-context

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vdaas/vald/vald-ci-container:nightly
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
          path: ${{ github.workspace }}
          set-safe-directory: true
      # - name: set git config
      #   run: |
      #     git config --global --add safe.directory ${GITHUB_WORKSPACE}
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 10
      #     path: $GITHUB_WORKSPACE
      - name: "Fetch golang version"
        id: golang_version
        run: |
          GO_VERSION=`make version/go`
          echo "version=${GO_VERSION}" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.golang_version.outputs.version }}
      - name: check
        run: go version && git version
