name: "Detect internal config changes"

on:
  
  # TODO: Delete it later.
  push:
    branches:
      - "add-dump-action"

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dump-context

  warning:
    runs-on: ubuntu-latest
    steps:
      - name: Warn
        run: |
          PR_COMMENTS=`curl ${API_URL}?per_page=10000`
          BODY=`echo -E $PR_COMMENTS | jq 'last(.[] | select(.user.login == "vdaas-ci") | select(.body | test("^\\\\*\\\\*\\\\[WARNING:INTCFG")) | .body)' -r`

          if [ "$BODY" = "null" ]; then
            curl --include --verbose --fail \
            -H "Accept: application/json" \
            -H "Content-Type:application/json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            --request POST \
            --data "{\"body\": \"**[WARNING:INTCFG]** Changes in \`interal/config\` may require you to change Helm charts. Please check.\"}" \
            ${API_URL}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
          API_URL: ${{ github.event.pull_request.comments_url }}
          PR_USER: ${{ github.event.pull_request.user.login }}
          PR_NUM: ${{ github.event.issue.number }}
