name: "Build docker image: helm-operator"

on:

  # TODO: Delete it later.
  push:
    branches:
      - "add-dump-action"

jobs:
  build:
    # Resuable workflow from my repo
    uses: ./.github/workflows/_docker-image.yaml
    with:
      target: operator/helm
