name: "Run E2E chaos test"

on:
  # TODO: Delete it later.
  push:
    branches:
      - "add-dump-action"

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dump-context

  agent-failure:
    name: "E2E chaos test (Agent failure: to test insert/search works even if one of the agents is failing)"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - name: Set up e2e environment
        uses: ./.github/actions/setup-e2e

      - name: Deploy Chaos Mesh
        uses: ./.github/actions/deploy-chaos-mesh
        with:
          helm_extra_options: "--set podChaos.failure.enabled=true"
  
  random-pod-failure:
    name: "E2E chaos test (random Pod failure: to test redundancy)"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - name: Set up e2e environment
        uses: ./.github/actions/setup-e2e

      - name: Deploy Chaos Mesh
        uses: ./.github/actions/deploy-chaos-mesh
        with:
          helm_extra_options: "--set podChaos.kill.enabled=true"
