name: "Run PR creation"
on:
  pull_request:
    types:
      - "labeled"

env:
  TARGET_LABEL_NAME_PREFIX: 'actions/backport/'
  HOOKED_LABEL_NAME: ${{ github.event.label.name }}

jobs:
  dump-contexts-to-log:
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled' && startsWith( env.HOOKED_LABEL_NAME, env.TARGET_LABEL_NAME_PREFIX ) # e.g.) actions/backport/v1.7
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dump-context

  create:
    runs-on: ubuntu-latest
    needs: [dump-contexts-to-log]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git config
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Set Github context
        id: set_context
        run: |
          RELEASE_BASE=`echo "$HOOKED_LABEL_NAME" | sed -e "s:^$TARGET_LABEL_NAME_PREFIX::"` # e.g) vx.x
          RELEASE_BRANCH_NAME=release/${RELEASE_BASE}                                        # e.g) release/vx.x
          BACKPORT_BRANCH_NAME=backport/${RELEASE_BASE}/${GITHUB_HEAD_REF}                   # e.g) backport/vx.x/{current branch name}

          echo "RELEASE_BASE=${RELEASE_BASE}"                  >> $GITHUB_OUTPUT
          echo "RELEASE_BRANCH_NAME=${RELEASE_BRANCH_NAME}"    >> $GITHUB_OUTPUT
          echo "BACKPORT_BRANCH_NAME=${BACKPORT_BRANCH_NAME}"  >> $GITHUB_OUTPUT

          echo "${RELEASE_BASE}"
          echo "${RELEASE_BRANCH_NAME}"
          echo "${BACKPORT_BRANCH_NAME}"
        env:
          HOOKED_LABEL_NAME: ${{ github.event.label.name }}

      - name: Create PR
        run: |
          echo hello
          # gh pr create --base master --head develop --title "Fix bug" --body ""
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCH_NAME: ${{ steps.set_context.outputs.RELEASE_BRANCH_NAME }}
          BACKPORT_BRANCH_NAME: ${{ steps.set_context.outputs.BACKPORT_BRANCH_NAME }}
