name: "Sync Vald"
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *"
jobs:
  sync:
    # TODO: change to the following before main merge.
    # uses: vdaas/vald-client-ci/.github/workflows/sync.yaml@main
    uses: vdaas/vald-client-ci/.github/workflows/sync.yaml@feat/add-common-workflows
    with:
      client_type: java
    secrets:
      CI_USER: ${{ secrets.DISPATCH_USER }}
      CI_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
